name: MultiVersion
api: 5.0.0
main: AkmalFairuz\MultiVersion\Loader
version: 3.0.0
description: A plugin to allows older Minecraft client versions to connect to newer server versions.
mcpe-protocol: [589, 594, 618]
author: AkmalFairuz
permissions:
  multiversion.command:
    default: op
